sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: YOUR_MYSQL_ROOT_PASSWORD  # Replace this with your actual MySQL root password
